### ISSUE TITLE
AttributeError: module 'streamlit' has no attribute 'cli'

### ISSUE THREAD

**Issue by Nicoautoxp** [mmcguffi/pLannotate#36]
Hi, 

I got an error when starting plannotate after installing it via mamba. I changed "import streamlit.cli" to "import streamlit.web.cli" and got it working again.

Could you perhaps tell me how i can start the application on a different port then 8501? I have some other streamlit applications running on other ports and there i just specify the port by adding ex. --server.port 7501. But this does not seem to work with plannotate.

Regards
Nicolas

**Comment by mmcguffi** [comment]
Hi @Nicoautoxp, please tell me your version of plannotate and what computing environment you are using.

As far as server ports, I am not sure -- if you want to look through it and open a pull request that would be great.

**Comment by mmcguffi** [comment]
closing this, but feel free to reopen if you still think that the `AttributeError: module 'streamlit' has no attribute 'cli'` is not fixed in v1.2.1
